// server/controllers/fileController.js
import archiver from 'archiver';
import streamBuffers from 'stream-buffers';
import { parseTextWithGemini } from '../Utils/geminiParser.js';

const fileController = {
  uploadAndParse: async (req, res) => {
    try {
      const { text } = req.body;
      if (!text) {
        return res.status(400).json({ error: 'No text provided' });
      }
      
      console.log('Received text for processing, length:', text.length);
      
      // Use Google Gemini to parse the text and determine file structure.
      const parsedData = await parseTextWithGemini(text);
      console.log('Gemini parsed data:', parsedData);
      
      if (!parsedData.files || parsedData.files.length === 0) {
        return res.status(400).json({ error: 'No files generated by Gemini.' });
      }
      
      // Create a ZIP archive with the generated files.
      const outputBuffer = new streamBuffers.WritableStreamBuffer();
      const archive = archiver('zip', { zlib: { level: 9 } });
      
      archive.pipe(outputBuffer);
      
      parsedData.files.forEach(file => {
        console.log(`Adding file: ${file.name}`);
        archive.append(file.content, { name: file.name });
      });
      
      await archive.finalize();
      
      const zipData = outputBuffer.getContents();
      if (!zipData) {
        return res.status(500).json({ error: 'Error generating ZIP file.' });
      }
      
      res.set('Content-Type', 'application/zip');
      res.set('Content-Disposition', 'attachment; filename=files.zip');
      console.log('Sending ZIP file to client.');
      return res.send(zipData);
      
    } catch (error) {
      console.error('Error in uploadAndParse:', error);
      return res.status(500).json({ error: 'Internal server error.' });
    }
  }
};

export default fileController;
