import { clerkClient } from '@clerk/express';
import archiver from 'archiver';
import streamBuffers from 'stream-buffers';
import { parseTextWithGemini } from '../Utils/geminiParser.js';
import User from '../Models/User.js';

const fileController = {
  uploadAndParse: async (req, res) => {
    try {
      const { userId } = req.auth;

      if (!userId) {
        return res.status(401).json({ error: 'Not authenticated. Please sign in.' });
      }

      const { text } = req.body;
      if (!text) {
        return res.status(400).json({ error: 'No text provided' });
      }
      console.log('Received text for processing, length:', text.length);

      let user = await User.findOne({ clerkUserId: userId });
      if (!user) {
        user = await User.create({ clerkUserId: userId });
      }

      // Set daily limit: free users get 4, paid users effectively unlimited
      const dailyLimit = user.plan === 'free' ? 3 : 999999;
      const today = new Date().toISOString().split('T')[0];
      let usageEntry = user.usage.find(u => u.date.toISOString().split('T')[0] === today);

      if (!usageEntry) {
        usageEntry = { date: new Date(), count: 0 };
        user.usage.push(usageEntry);
      }

      if (usageEntry.count >= dailyLimit) {
        // Updated error message when the limit is exceeded
        return res.status(403).json({ error: 'Daily limit reached. Please buy a plan to unlock additional usage.' });
      }

      const parsedData = await parseTextWithGemini(text);
      console.log('Gemini parsed data:', parsedData);

      if (!parsedData.files || parsedData.files.length === 0) {
        return res.status(400).json({ error: 'No files generated by Gemini.' });
      }

      // Increment usage and save user record
      usageEntry.count += 1;
      await user.save();

      const outputBuffer = new streamBuffers.WritableStreamBuffer();
      const archive = archiver('zip', { zlib: { level: 9 } });

      archive.pipe(outputBuffer);

      parsedData.files.forEach((file) => {
        console.log(`Adding file: ${file.name}`);
        archive.append(file.content, { name: file.name });
      });

      await archive.finalize();

      const zipData = outputBuffer.getContents();
      if (!zipData) {
        return res.status(500).json({ error: 'Error generating ZIP file.' });
      }

      res.set('Content-Type', 'application/zip');
      res.set('Content-Disposition', 'attachment; filename=files.zip');
      console.log('Sending ZIP file to client.');
      return res.send(zipData);
    } catch (error) {
      console.error('Error in uploadAndParse:', error);
      return res.status(500).json({ error: 'Internal server error.' });
    }
  },
};

export default fileController;
